version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: agentic-workflow-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: development_password
      POSTGRES_DB: agentic_workflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # For running real integration tests locally
  test-postgres:
    image: postgres:15-alpine
    container_name: agentic-workflow-test-db
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_agentic_workflow
    ports:
      - "5433:5432"  # Different port for test database
    tmpfs:
      - /var/lib/postgresql/data  # Use tmpfs for faster test runs
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local